// Tự sinh từ migrations/0001_init.sql — đừng sửa tay.
export const CAU_LENH_TAO_BANG = [
  "CREATE TABLE IF NOT EXISTS access_control ( email TEXT PRIMARY KEY, trang_thai TEXT NOT NULL DEFAULT 'cho_duyet', ten TEXT, ngay_yeu_cau TEXT, ngay_duyet TEXT, la_chu INTEGER NOT NULL DEFAULT 0 )",
  "CREATE TABLE IF NOT EXISTS config_list ( id INTEGER PRIMARY KEY AUTOINCREMENT, loai TEXT NOT NULL, gia_tri TEXT NOT NULL, thu_tu INTEGER NOT NULL DEFAULT 0, UNIQUE (loai, gia_tri) )",
  "CREATE INDEX IF NOT EXISTS ix_config_loai ON config_list (loai, thu_tu)",
  "CREATE TABLE IF NOT EXISTS hoc_vien ( id INTEGER PRIMARY KEY AUTOINCREMENT, ten TEXT NOT NULL, ngay_chia_se_cuoi TEXT, ngay_dau_chia_se TEXT, dia_chi TEXT, ndd1 TEXT, ndd2 TEXT, ndd3 TEXT, khu_vuc TEXT, tien_do TEXT, danh_gia TEXT, cap_nhat_luc TEXT )",
  "CREATE INDEX IF NOT EXISTS ix_hv_khuvuc ON hoc_vien (khu_vuc)",
  "CREATE INDEX IF NOT EXISTS ix_hv_tiendo ON hoc_vien (tien_do)",
  "CREATE INDEX IF NOT EXISTS ix_hv_ten ON hoc_vien (ten)",
  "CREATE TABLE IF NOT EXISTS nhat_ky_don_thuan ( id INTEGER PRIMARY KEY AUTOINCREMENT, ngay TEXT NOT NULL, khu_vuc TEXT NOT NULL, don_thuan INTEGER NOT NULL DEFAULT 0, ghi_chu TEXT, ndd1 TEXT, ndd2 TEXT, ndd3 TEXT )",
  "CREATE INDEX IF NOT EXISTS ix_nkdt_ngay ON nhat_ky_don_thuan (ngay, khu_vuc)",
  "CREATE TABLE IF NOT EXISTS muc_tieu_kv ( thang TEXT NOT NULL, khu_vuc TEXT NOT NULL, mt_don_thuan INTEGER NOT NULL DEFAULT 0, mt_huu_hieu INTEGER NOT NULL DEFAULT 0, mt_bt INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (thang, khu_vuc) )",
  "CREATE TABLE IF NOT EXISTS muc_tieu_ca_nhan ( thang TEXT NOT NULL, khu_vuc TEXT NOT NULL, ten TEXT NOT NULL, mt_don_thuan INTEGER NOT NULL DEFAULT 0, mt_huu_hieu INTEGER NOT NULL DEFAULT 0, mt_bt INTEGER NOT NULL DEFAULT 0, mt_tt127_ngay INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (thang, khu_vuc, ten) )",
  "CREATE TABLE IF NOT EXISTS tp_tho_phuong ( thang TEXT NOT NULL, khu_vuc TEXT NOT NULL, loai TEXT NOT NULL, tuan INTEGER NOT NULL, so_luong INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (thang, khu_vuc, loai, tuan) )",
  "CREATE TABLE IF NOT EXISTS tp_bao_cao ( thang TEXT NOT NULL, khu_vuc TEXT NOT NULL, tuan INTEGER NOT NULL, nhom TEXT NOT NULL, thoi_gian TEXT NOT NULL, thoi_gian_ms INTEGER NOT NULL, snap_1lan INTEGER NOT NULL DEFAULT 0, snap_4lan INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (thang, khu_vuc, tuan, nhom) )",
  "CREATE TABLE IF NOT EXISTS giao_duc_thanh_vien ( thang TEXT NOT NULL, khu_vuc TEXT NOT NULL, ten TEXT NOT NULL, tuan INTEGER NOT NULL, edu_lms TEXT, tt127_ngay INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (thang, khu_vuc, ten, tuan) )",
  "CREATE INDEX IF NOT EXISTS ix_gdtv_thang_kv ON giao_duc_thanh_vien (thang, khu_vuc)",
  "CREATE TABLE IF NOT EXISTS diem_danh ( thang TEXT NOT NULL, khu_vuc TEXT NOT NULL, ten TEXT NOT NULL, tuan INTEGER NOT NULL, buoi TEXT NOT NULL, gia_tri TEXT NOT NULL, PRIMARY KEY (thang, khu_vuc, ten, tuan, buoi) )",
  "CREATE INDEX IF NOT EXISTS ix_dd_thang_kv ON diem_danh (thang, khu_vuc)",
  "CREATE TABLE IF NOT EXISTS diem_danh_roster ( id INTEGER PRIMARY KEY AUTOINCREMENT, khu_vuc TEXT NOT NULL, ten TEXT NOT NULL, phu_huynh TEXT, thu_tu INTEGER NOT NULL DEFAULT 0, UNIQUE (khu_vuc, ten) )",
  "CREATE INDEX IF NOT EXISTS ix_ddr_kv ON diem_danh_roster (khu_vuc, thu_tu)",
  "CREATE TABLE IF NOT EXISTS diem_danh_ghi_chu ( khu_vuc TEXT NOT NULL, ten TEXT NOT NULL, ma_cap_do TEXT, ghi_chu TEXT, ngay_cap_nhat TEXT, PRIMARY KEY (khu_vuc, ten) )",
  "CREATE TABLE IF NOT EXISTS lich_lam_viec ( id INTEGER PRIMARY KEY AUTOINCREMENT, ngay TEXT NOT NULL, gio_bat_dau TEXT, gio_ket_thuc TEXT, noi_dung TEXT NOT NULL, nguoi_phu_trach TEXT, khu_vuc TEXT, dia_diem TEXT, trang_thai TEXT, nguoi_tham_gia TEXT )",
  "CREATE INDEX IF NOT EXISTS ix_lich_ngay ON lich_lam_viec (ngay)",
  "CREATE TABLE IF NOT EXISTS dao_tao_tien_do ( khu_vuc TEXT NOT NULL, ten TEXT NOT NULL, bai_da_hoc TEXT, ngay_cap_chung_chi TEXT, PRIMARY KEY (khu_vuc, ten) )",
  "CREATE TABLE IF NOT EXISTS dao_tao_viec_giao ( id INTEGER PRIMARY KEY AUTOINCREMENT, khu_vuc TEXT NOT NULL, ten TEXT NOT NULL, noi_dung TEXT NOT NULL, ngay_giao TEXT, han_hoan_thanh TEXT, trang_thai TEXT )",
  "CREATE INDEX IF NOT EXISTS ix_dtvg_kv ON dao_tao_viec_giao (khu_vuc, ten)",
  "CREATE TABLE IF NOT EXISTS le_hoi_cau_hinh ( ma_le_hoi TEXT PRIMARY KEY, ten_le_hoi TEXT NOT NULL, ngay_bat_dau TEXT, ngay_ket_thuc TEXT, danh_sach_bai TEXT, so_lan_yeu_cau INTEGER NOT NULL DEFAULT 1 )",
  "CREATE TABLE IF NOT EXISTS le_hoi_tien_do ( ma_le_hoi TEXT NOT NULL, khu_vuc TEXT NOT NULL, ten TEXT NOT NULL, da_phat_bieu TEXT, ngay_hoan_thanh TEXT, PRIMARY KEY (ma_le_hoi, khu_vuc, ten) )",
  "CREATE TABLE IF NOT EXISTS phien_dang_nhap ( token TEXT PRIMARY KEY, email TEXT NOT NULL, ten TEXT, tao_luc INTEGER NOT NULL, het_han_luc INTEGER NOT NULL )",
  "CREATE INDEX IF NOT EXISTS ix_phien_email ON phien_dang_nhap (email)",
  "CREATE TABLE IF NOT EXISTS so_moc ( id INTEGER PRIMARY KEY AUTOINCREMENT, moc TEXT NOT NULL, ngay TEXT NOT NULL, thang TEXT NOT NULL, ten TEXT NOT NULL, khu_vuc TEXT NOT NULL, ndd1 TEXT, ndd2 TEXT, ndd3 TEXT, ghi_chu TEXT, nguoi_ghi TEXT, tao_luc INTEGER NOT NULL, UNIQUE (moc, ten, khu_vuc) )",
  "CREATE INDEX IF NOT EXISTS ix_so_moc_ngay ON so_moc (ngay, moc)",
  "CREATE INDEX IF NOT EXISTS ix_so_moc_thang ON so_moc (thang, moc)",
  "CREATE TABLE IF NOT EXISTS chot_ky ( ky TEXT PRIMARY KEY, tu_ngay TEXT NOT NULL, den_ngay TEXT NOT NULL, khu_vuc TEXT, bang_json TEXT NOT NULL, tom_tat_json TEXT, nguoi_chot TEXT, chot_luc INTEGER NOT NULL )",
  "CREATE TABLE IF NOT EXISTS cv_cong_viec ( khu_vuc TEXT NOT NULL, ten TEXT NOT NULL, thang TEXT NOT NULL, tuan INTEGER NOT NULL, buoi TEXT NOT NULL, ngay TEXT NOT NULL, gia_tri TEXT NOT NULL, PRIMARY KEY (khu_vuc, ten, thang, tuan, buoi, ngay) )",
  "CREATE INDEX IF NOT EXISTS ix_cvcv_kv_thang ON cv_cong_viec (khu_vuc, thang)",
  "CREATE TABLE IF NOT EXISTS cv_nguoi ( khu_vuc TEXT NOT NULL, ten TEXT NOT NULL, kieu TEXT NOT NULL, thu_tu INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (khu_vuc, ten) )"
];
